CREATE TABLE USERS 
(
  USER_ID NUMBER(8, 0) NOT NULL 
, USER_NAME VARCHAR2(50 BYTE) NOT NULL 
, USER_PASSWORD VARCHAR2(20 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX USERS_PK ON USERS (USER_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX USERS_UK1 ON USERS (USER_NAME ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE USERS
ADD CONSTRAINT USERS_PK PRIMARY KEY 
(
  USER_ID 
)
USING INDEX USERS_PK
ENABLE;

ALTER TABLE USERS
ADD CONSTRAINT USERS_UK1 UNIQUE 
(
  USER_NAME 
)
USING INDEX USERS_UK1
ENABLE;
