CREATE USER TIMETASKMANAGER IDENTIFIED BY 12345;
GRANT CREATE TABLE TO TIMETASKMANAGER;
GRANT CREATE TRIGGER TO TIMETASKMANAGER;
GRANT CREATE SEQUENCE TO TIMETASKMANAGER;
GRANT CREATE SESSION TO TIMETASKMANAGER;