CREATE USER TIMETASKMANAGER1 IDENTIFIED BY 12345;
GRANT CREATE TABLE TO TIMETASKMANAGER1;
GRANT CREATE TRIGGER TO TIMETASKMANAGER1;
GRANT CREATE SEQUENCE TO TIMETASKMANAGER1;
GRANT CREATE SESSION TO TIMETASKMANAGER1;