--------------------------------------------------------
--  File created - понедельник-апреля-24-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TASKS
--------------------------------------------------------

  CREATE TABLE "TIMETASKMANAGER"."TASKS" 
   (	"TASK_ID" NUMBER(9,0), 
	"PARENT_TASK_ID" NUMBER(9,0), 
	"CHILD_TASK_ID" NUMBER(9,0), 
	"TASK_LEVEL" NUMBER(9,0), 
	"USER_ID" NUMBER(9,0), 
	"TASK_NAME" VARCHAR2(100 BYTE), 
	"PLAN_START_TIME" DATE, 
	"PLAN_END_TIME" DATE, 
	"PLAN_DURATION" NUMBER(9,0), 
	"FACT_START_TIME" DATE, 
	"FACT_END_TIME" DATE, 
	"FACT_DURATION" NUMBER(9,0), 
	"NUM_VERSION" NUMBER(9,0), 
	"IS_COMPLETED" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "TIMETASKMANAGER"."USERS" 
   (	"USER_ID" NUMBER(9,0), 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"USER_PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TASKS
--------------------------------------------------------

   CREATE SEQUENCE  "TIMETASKMANAGER"."SEQ_TASKS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USERS
--------------------------------------------------------

   CREATE SEQUENCE  "TIMETASKMANAGER"."SEQ_USERS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Index USERS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIMETASKMANAGER"."USERS_UK1" ON "TIMETASKMANAGER"."USERS" ("USER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TASKS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIMETASKMANAGER"."TASKS_PK" ON "TIMETASKMANAGER"."TASKS" ("TASK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIMETASKMANAGER"."USERS_PK" ON "TIMETASKMANAGER"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "TIMETASKMANAGER"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TIMETASKMANAGER"."USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "TIMETASKMANAGER"."USERS" MODIFY ("USER_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "TIMETASKMANAGER"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TIMETASKMANAGER"."USERS" ADD CONSTRAINT "USERS_UK1" UNIQUE ("USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TASKS
--------------------------------------------------------

  ALTER TABLE "TIMETASKMANAGER"."TASKS" ADD CONSTRAINT "TASKS_PK" PRIMARY KEY ("TASK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TIMETASKMANAGER"."TASKS" MODIFY ("IS_COMPLETED" NOT NULL ENABLE);
  ALTER TABLE "TIMETASKMANAGER"."TASKS" MODIFY ("NUM_VERSION" NOT NULL ENABLE);
  ALTER TABLE "TIMETASKMANAGER"."TASKS" MODIFY ("PLAN_DURATION" NOT NULL ENABLE);
  ALTER TABLE "TIMETASKMANAGER"."TASKS" MODIFY ("TASK_NAME" NOT NULL ENABLE);
  ALTER TABLE "TIMETASKMANAGER"."TASKS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TIMETASKMANAGER"."TASKS" MODIFY ("CHILD_TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "TIMETASKMANAGER"."TASKS" MODIFY ("PARENT_TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "TIMETASKMANAGER"."TASKS" MODIFY ("TASK_ID" NOT NULL ENABLE);
