CREATE TABLE TASKS 
(
  ROOT_TASK_ID NUMBER(8, 0) NOT NULL 
, PARENT_SUBTASK_ID NUMBER(8, 0) NOT NULL 
, CHILD_SUBTASK_ID NUMBER(8, 0) NOT NULL 
, LEVEL_SUBTASK_ID NUMBER(8, 0) 
, USER_ID NUMBER(8, 0) NOT NULL 
, TASK_NAME VARCHAR2(100 BYTE) NOT NULL 
, PLAN_START_TIME DATE 
, PLAN_END_TIME DATE 
, PLAN_DURATION NUMBER(8, 0) NOT NULL 
, FACT_START_TIME DATE 
, FACT_END_TIME DATE 
, FACT_DURATION NUMBER(8, 0) NOT NULL 
, VERSION NUMBER(8, 0) NOT NULL 
, IS_COMPLETED VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
